# Site Settings
theme: jekyll-theme-midnight
title: ÖBB Fleet CMS Project
description: A Jekyll-based fleet management overview for the Austrian Federal Railways. Part of the CMS System course module.